# Dont upload this file to github
spring:
  application:
    name: petAppServer

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/petmate?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Flyway is managing the schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/test-mobile-app-8c2ce

  jackson:
    serialization:
      write-dates-as-timestamps: false

  cloudinary:
    cloud-name: do3nktaxg
    api-key: 922563787399544
    api-secret: jIkB12D4XBjCZidV_0UiAvgkFeI

server:
  port: 8080

firebase:
  credentials:
    path: classpath:firebase-config.json

groq:
  api:
    key: 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
    url: https://api.groq.com/openai/v1/chat/completions
  model:
    id: openai/gpt-oss-120b
