DELETE FROM red_list_species;

INSERT INTO red_list_species (category, breed_keyword, synonyms, protection_level, description) VALUES
('OTHER', 'Cá sấu nước lợ', '["Cá sấu hoa cà", "Crocodylus porosus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cá sấu nước ngọt', '["Cá sấu xiêm", "Crocodylus siamensis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Tắc kè đuôi vàng', '["Cnemaspis psychedelica"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Thằn lằn cá sấu', '["Shinisaurus crocodilurus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Kỳ đà vân', '["Varanus nebulosus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rắn hổ chúa', '["Rắn hổ mang chúa", "Ophiophagus hannah"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa ba-ta-gua miền nam', '["Batagur affinis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa hộp trán vàng miền trung', '["Rùa hộp bua-rê", "Cuora bourreti"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa hộp ba vạch', '["Rùa vàng", "Cuora cyclornata"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa hộp trán vàng miền bắc', '["Cuora galbinifrons"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa hộp trán vàng miền nam', '["Rùa hộp việt nam", "Cuora picturata"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa trung bộ', '["Mauremys annamensis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa đầu to', '["Platysternon megacephalum"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Giải', '["Pelochelys cantorii"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Giải sin-hoe', '["Rafetus swinhoei"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Bồ câu ni-cô-ba', '["Caloenas nicobarica"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Cò trắng trung quốc', '["Egretta eulophotes"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Vạc hoa', '["Gorsachius magnificus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Bồ nông chân xám', '["Pelecanus philippensis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Cò thìa', '["Platalea minor"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Quắm cánh xanh', '["Pseudibis davisoni"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Quắm lớn', '["Cò quắm lớn", "Thaumatibis gigantea"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Cắt lớn', '["Falco peregrinus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Rẽ mỏ thìa', '["Calidris pygmaea"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Choắt lớn mỏ vàng', '["Tringa guttifer"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Cổ rắn', '["Anhinga melanogaster"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Gà so cổ hung', '["Arborophila davidi"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Gà lôi lam mào trắng', '["Lophura edwardsi"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Gà lôi trắng', '["Lophura nycthemera"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Công', '["Pavo muticus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Gà tiền mặt vàng', '["Polyplectron bicalcaratum"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Gà tiền mặt đỏ', '["Polyplectron germaini"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Trĩ sao', '["Rheinardia ocellata"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Gà lôi tía', '["Tragopan temminckii"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Hạc cổ trắng', '["Ciconia episcopus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Già đẫy nhỏ', '["Leptoptilos javanicus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Cò lạo xám', '["Mycteria cinerea"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Niệc cổ hung', '["Aceros nipalensis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Niệc nâu', '["Anorrhinus austeni"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Niệc mỏ vằn', '["Rhyticeros undulatus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Hồng hoàng', '["Buceros bicornis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Ngan cánh trắng', '["Asarcornis scutulata"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Ô tác', '["Houbaropsis bengalensis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Khướu konkakinh', '["Ianthocincla konkakinhensis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Mi núi bà', '["Laniellus langbianis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Khướu ngọc linh', '["Trochalopteron ngoclinhense"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Khướu đầu đen má xám', '["Trochalopteron yersini"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Sếu đầu đỏ', '["Sếu cổ trụi", "Grus antigone"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Đại bàng đầu nâu', '["Aquila heliaca"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Kền kền ben gan', '["Gyps bengalensis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Kền kền ấn độ', '["Gyps indicus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Ó tai', '["Sarcogyps calvus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Chồn bay', '["Cầy bay", "Galeopterus variegatus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Voi châu á', '["Elephas maximus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Vượn má vàng trung bộ', '["Nomascus annamensis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Vượn đen tuyền tây bắc', '["Nomascus concolor"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Vượn đen má hung', '["Nomascus gabriellae"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Vượn đen má trắng', '["Nomascus leucogenys"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Vượn đen tuyền đông bắc', '["Vượn cao vít", "Nomascus nasutus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Vượn đen siki', '["Nomascus siki"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cu li lớn', '["Nycticebus bengalensis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cu li nhỏ', '["Nycticebus pygmaeus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Chà vá chân xám', '["Pygathrix cinerea"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Chà vá chân nâu', '["Pygathrix nemaeus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Chà vá chân đen', '["Pygathrix nigripes"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Voọc mũi hếch', '["Rhinopithecus avunculus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Voọc xám', '["Trachypithecus crepusculus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Voọc mông trắng', '["Trachypithecus delacouri"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Voọc đen má trắng', '["Trachypithecus francoisi"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Voọc bạc đông dương', '["Trachypithecus germaini"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Voọc đen hà tĩnh', '["Voọc gáy trắng", "Trachypithecus hatinhensis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Voọc bạc trường sơn', '["Trachypithecus margarita"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Voọc cát bà', '["Voọc đen đầu vàng", "Trachypithecus poliocephalus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Hươu vàng', '["Axis porcinus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Bò tót', '["Bos gaurus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Bò rừng', '["Bos javanicus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Sơn dương', '["Capricornis milneedwardsii"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Hươu xạ', '["Moschus berezovskii"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Mang trường sơn', '["Muntiacus truongsonensis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Mang lớn', '["Muntiacus vuquangensis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Sao la', '["Pseudoryx nghetinhensis"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Nai cà tong', '["Rucervus eldii"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Tê giác một sừng', '["Rhinoceros sondaicus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Tê tê java', '["Manis javanica"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Tê tê vàng', '["Manis pentadactyla"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Thỏ vằn', '["Nesolagus timminsi"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Chó rừng', '["Canis aureus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Sói đỏ', '["Chó sói lửa", "Cuon alpinus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cáo lửa', '["Vulpes vulpes"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Gấu chó', '["Helarctos malayanus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Gấu ngựa', '["Ursus thibetanus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rái cá vuốt bé', '["Aonyx cinereus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rái cá thường', '["Lutra lutra"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rái cá lông mũi', '["Lutra sumatrana"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rái cá lông mượt', '["Lutrogale perspicillata"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cầy mực', '["Arctictis binturong"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cầy văn bắc', '["Cầy vằn", "Chrotogale owstoni"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cầy gấm', '["Prionodon pardicolor"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cầy giông đốm lớn', '["Viverra megaspila"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Báo lửa', '["Beo lửa", "Catopuma temminckii"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Báo gấm', '["Neofelis nebulosa"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Báo hoa mai', '["Panthera pardus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Hổ đông dương', '["Panthera tigris corbetti"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Mèo gấm', '["Pardofelis marmorata"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Mèo cá', '["Prionailurus viverrinus"]', 'PROHIBITED', 'Thuộc Nhóm IB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cua bay việt nam', '["Cheirotonus battareli"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cua bay đen', '["Cheirotonus jansoni"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Bướm phượng đuôi kiếm răng nhọn', '["Teinopalpus aureus"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Bướm phượng đuôi kiếm răng tù', '["Teinopalpus imperialis"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Bướm phượng cánh chim chấm rời', '["Troides aeacus"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Bướm phượng cánh chim chấm liền', '["Troides helena"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cá cóc', '["giống Paramesotriton", "Paramesotriton spp."]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Tắc kè hoa', '["Gecko gecko"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Thạch sùng mí', '["giống Goniurosaurus", "Goniurosaurus spp."]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rắn hổ mang trung quốc', '["Naja atra"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rắn hổ mang một mắt kính', '["Naja kaouthia"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rắn hổ mang xiêm', '["Naja siamensis"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rắn ráo trâu', '["Ptyas mucosus"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Trăn cộc', '["Python brongersmai"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Trăn đất', '["Python molurus"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Trăn gấm', '["Python reticulatus"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Kỳ đà hoa', '["Varanus salvator"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cua đinh', '["Ba ba nam bộ", "Amyda cartilaginea"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Ba ba gai', '["Palea steindachneri"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa hộp lưng đen', '["Cuora amboinensis"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa sa nhân', '["Cuora mouhotii"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa đất châu á', '["Cyclemys dentata"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa đất sê-pôn', '["Cyclemys oldhami"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa đất pul-kin', '["Cyclemys puichristriata"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa đất speng-le-ri', '["Geomyda spengleri"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa răng', '["Heosemys annandalii"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa đất lớn', '["Heosemys grandis"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa núi vàng', '["Indotestudo elongata"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa ba gờ', '["Malayemys subtrijuga"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa núi viền', '["Manouria impressa"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa câm', '["Mauremys mutica"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa đầm cổ đỏ', '["Mauremys nigricans"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa bốn mắt', '["Sacalia quadriocellata"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Rùa cổ bự', '["Siebenrockiella crassicollis"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Bồ câu nâu', '["Columba punicea"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Cò quăm đầu đen', '["Threskiornis melanocephalus"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Các loài trong bộ Cắt', '["trừ Cắt lớn", "Falconiformes spp."]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Các loài trong bộ Cú', '["Strigiformes spp."]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Gà so, gà lôi', '["giống Arborophila", "Lophura", "Arborophila spp.", "Lophura spp."]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Hạc đen', '["Ciconia nigra"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Già đẫy lớn', '["Leptoptilos dubius"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Họ Hồng hoàng', '["các loài còn lại", "Bucerotidae spp."]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Vịt đầu đen', '["Aythya baeri"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Vịt mỏ nhọn', '["Mergus squamatus"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Sẻ đồng ngực vàng', '["Emberiza aureola"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Khướu', '["Garrulax", "Trochalopteron", "Pterorhinus", "Ianthocincla", "Garrulax spp."]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Nhồng', '["Yểng", "Gracula religiosa"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Kim oanh tai bạc', '["Leiothrix argentauris"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Kim oanh mỏ đỏ', '["Leiothrix lutea"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Đuôi cụt', '["giống Pitta", "Hydronis", "Pitta spp."]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Chân bơi', '["Heliopais personatus"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Các loài trong bộ Ưng', '["trừ 4 loài đã liệt kê IB", "Accipitriformes spp."]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Vẹt', '["giống Psittacula", "Psittacula spp."]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('BIRDS', 'Vẹt lùn', '["Loriculus vernalis"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Dơi ngựa bé', '["Pteropus hypomelanus"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Dơi ngựa ly-lei', '["Pteropus lylei"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Dơi ngựa lớn', '["Pteropus vampyrus"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Chuột đá', '["Laonastes aenigmamus"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Sóc bay trâu', '["Petaurista philippensis"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Sóc đen', '["Ratufa bicolor"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Khỉ mặt đỏ', '["Macaca arctoides"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Khỉ mốc', '["Macaca assamensis"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Khỉ đuôi dài', '["Macaca fascicularis"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Khỉ đuôi lợn', '["Macaca leonina"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Khỉ vàng', '["Macaca mulatta"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Mang pù hoạt', '["Muntiacus puhoatensis"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Nai', '["Rusa unicolor"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cheo cheo', '["Tragulus kanchil"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cheo cheo lưng bạc', '["Tragulus versicolor"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Thỏ rừng', '["Lepus sinensis"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Lửng lợn', '["Arctonyx collaris"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cầy tai trắng', '["Arctogalidia trivirgata"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Triết chỉ lưng', '["Mustela strigidorsa"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Lửng chó', '["Nyctereutes procyonoides"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cầy vòi mốc', '["Paguma larvata"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cầy vòi hương', '["Paradoxurus hermaphroditus"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cầy giông', '["Viverra zibetha"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Cầy hương', '["Viverricula indica"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Mèo ri', '["Felis chaus"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.'),
('OTHER', 'Mèo rừng', '["Prionailurus bengalensis"]', 'RESTRICTED', 'Thuộc Nhóm IIB - Danh mục động vật rừng nguy cấp, quý, hiếm theo Nghị định 84/2021/NĐ-CP.');
